import os
import subprocess
import json
import google.generativeai as genai

class SubtitleGenerator:
    def __init__(self, api_key):
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-1.5-flash')

    def generate_srt(self, transcript, clip_start, clip_end, output_path):
        """
        Generates an SRT file using Gemini for optimization.
        """
        words = []
        for segment in transcript.get('segments', []):
            for word_info in segment.get('words', []):
                if word_info['end'] > clip_start and word_info['start'] < clip_end:
                    # Adjust times to be relative to the clip start
                    word_info_copy = word_info.copy()
                    word_info_copy['start'] -= clip_start
                    word_info_copy['end'] -= clip_start
                    words.append(word_info_copy)

        if not words:
            return False

        word_data = [{"word": w["word"], "start": w["start"], "end": w["end"]} for w in words]
        words_json = json.dumps(word_data, indent=2)

        prompt = f"""
        You are an expert SRT subtitle creator for viral social media videos.
        Your task is to take a JSON array of words with timestamps and create an optimized SRT file content.

        Guidelines:
        1.  **Grouping**: Group words into short, punchy lines. A line should not exceed 3-4 words or 25 characters if possible.
        2.  **Timing**: The start time of a subtitle line is the start time of its first word. The end time is the end time of its last word.
        3.  **Engagement**: You can add relevant emojis at the end of lines if it fits the context.
        4.  **Format**: The output must be a valid SRT format. Each block should have an index, a timestamp line (HH:MM:SS,ms --> HH:MM:SS,ms), and the text line(s). The final output should be a raw string containing the SRT content.

        INPUT WORDS (JSON):
        ---
        {words_json}
        ---

        OUTPUT (SRT content as a raw string):
        """
        try:
            response = self.model.generate_content(prompt)
            srt_content = response.text.strip()
            
            # Basic validation
            if "-->" not in srt_content:
                raise ValueError("Generated text is not in SRT format.")

            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(srt_content)
            print(f"✅ SRT file generated by Gemini: {output_path}")
            return True
        except Exception as e:
            print(f"❌ Error creating SRT with Gemini: {e}")
            print("Falling back to simple SRT generation.")
            return self._generate_srt_simple(transcript, clip_start, clip_end, output_path)

    def _generate_srt_simple(self, transcript, clip_start, clip_end, output_path, max_chars=20, max_duration=2.0):
        words = []
        for segment in transcript.get('segments', []):
            for word_info in segment.get('words', []):
                if word_info['end'] > clip_start and word_info['start'] < clip_end:
                    words.append(word_info)
        
        if not words:
            return False

        srt_content = ""
        index = 1
        
        current_block = []
        block_start = None
        
        for i, word in enumerate(words):
            start = max(0, word['start'] - clip_start)
            end = max(0, word['end'] - clip_start)
            
            if not current_block:
                current_block.append(word)
                block_start = start
            else:
                current_text_len = sum(len(w['word']) + 1 for w in current_block)
                duration = end - block_start
                
                if current_text_len + len(word['word']) > max_chars or duration > max_duration:
                    block_end = current_block[-1]['end'] - clip_start
                    text = " ".join([w['word'] for w in current_block]).strip()
                    srt_content += self._format_srt_block(index, block_start, block_end, text)
                    index += 1
                    
                    current_block = [word]
                    block_start = start
                else:
                    current_block.append(word)
        
        if current_block:
            block_end = current_block[-1]['end'] - clip_start
            text = " ".join([w['word'] for w in current_block]).strip()
            srt_content += self._format_srt_block(index, block_start, block_end, text)
            
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(srt_content)
            
        return True

    def _format_srt_block(self, index, start, end, text):
        def format_time(seconds):
            hours = int(seconds // 3600)
            minutes = int((seconds % 3600) // 60)
            secs = int(seconds % 60)
            millis = int((seconds - int(seconds)) * 1000)
            return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"
            
        return f"{index}\n{format_time(start)} --> {format_time(end)}\n{text}\n\n"

    def burn_subtitles(self, video_path, srt_path, output_path, alignment=2, fontsize=16):
        """
        Burns subtitles into the video using FFmpeg.
        Alignment: 2 (Bottom), 5 (Middle), 8 (Top)
        """
        ass_alignment = 2
        align_lower = str(alignment).lower()
        if align_lower == 'top': 
            ass_alignment = 8
        elif align_lower == 'middle': 
            ass_alignment = 5

        final_fontsize = int(fontsize * 0.8) 
        if final_fontsize < 10: final_fontsize = 10

        try:
            safe_srt_path = srt_path.replace('\\', '/').replace(':', '\\:')
        except:
            safe_srt_path = srt_path

        style_string = f"Alignment={ass_alignment},Fontname=Verdana,Fontsize={final_fontsize},PrimaryColour=&H00FFFFFF,OutlineColour=&H60000000,BackColour=&H00000000,BorderStyle=3,Outline=1,Shadow=0,MarginV=25,Bold=1"
        
        cmd = [
            'ffmpeg', '-y',
            '-i', video_path,
            '-vf', f"subtitles='{safe_srt_path}':force_style='{style_string}'",
            '-c:a', 'copy',
            '-c:v', 'libx264', '-preset', 'fast', '-crf', '23',
            output_path
        ]
        
        print(f"🎬 Burning subtitles: {' '.join(cmd)}")
        result = subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        
        if result.returncode != 0:
            print(f"❌ FFmpeg Subtitle Error: {result.stderr.decode()}")
            raise Exception(f"FFmpeg failed: {result.stderr.decode()}")

        return True
